# Generated by Django 3.1.3 on 2021-01-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker',
            old_name='User',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='tracker',
            name='action',
            field=models.CharField(choices=[('Credited', 'Credited by'), ('Debited', 'Debited by')], max_length=10),
        ),
    ]
